#define x using
#define xx namespace
#define xxx std
#define xxxx const
#define xxxxx string
#define xxxxxx strs
#define xxxxxxx =
#define xxxxxxxx "@@@@!@@@%@!@!%@@@@$"
#define xxxxxxxxx vector<int>
#define xxxxxxxxxx ascii_values
#define xxxxxxxxxxx &
#define xxxxxxxxxxxx str
#define xxxxxxxxxxxxx ascii_vals
#define xxxxxxxxxxxxxx for
#define xxxxxxxxxxxxxxx auto
#define xxxxxxxxxxxxxxxx char
#define xxxxxxxxxxxxxxxxx ch
#define xxxxxxxxxxxxxxxxxx push_back
#define xxxxxxxxxxxxxxxxxxx return
#define xxxxxxxxxxxxxxxxxxxx int
#define xxxxxxxxxxxxxxxxxxxxx ffunction
#define xxxxxxxxxxxxxxxxxxxxxx result
#define xxxxxxxxxxxxxxxxxxxxxxx arr
#define xxxxxxxxxxxxxxxxxxxxxxxx brr
#define xxxxxxxxxxxxxxxxxxxxxxxxx size
#define xxxxxxxxxxxxxxxxxxxxxxxxxx main
#define xxxxxxxxxxxxxxxxxxxxxxxxxxx freopen
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxx "flag.txt"
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxx "r"
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx stdin
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "output.txt"
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "w"
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx stdout
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx flag
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx cin
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx cout
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx i
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 0
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ++
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx )
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx [
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ]
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx {
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx }
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ;
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx .
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx :
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ,
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx <<
#define xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx >>